# dvc.yaml
stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - src/utils.py
      - params.yaml
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - src/utils.py
      - data/raw
      - params.yaml
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - src/utils.py
      - data/processed
      - params.yaml
    outs:
      - data/features

  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - src/utils.py
      - data/features
      - params.yaml
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - src/utils.py
      - models/model.pkl
      - data/features
      - params.yaml
    metrics:
      - evaluation/metrics.json:
          cache: false
    outs:
      - evaluation/confusion_matrix.png
      - evaluation/classification_report.csv